### ISSUE TITLE
Unterscheidung Öffnungswinkel vs vollständige Öffnen/Schließen 

### ISSUE THREAD

**Issue by bekaxe** [chrkan/homatic-somfy#1]
Hallo, 

ich habe meine Somfy Jalousien (RTS Zwischenstecker) erfolgreich über den CUL-Stick verbunden und anhand der Anleitung eingelernt.  (Raspberrymatic mit CUxD auf PI)
Funktioniert soweit auch, allerdings: 
 
- einmaliges Drücken der Hoch/Runtertaster lässt die Jalousie nur ein kleines Stück bewegen, analog zum Scroll-Rad an der Somfy Telis Fernbedienung. 
- vollständiges öffnen/schließen funktioniert teilweise durch 3-maliges, schnell-hintereinander Drücken. Oft reagiert das System aber zu langsam und es bewegt sich nur 3x kurz.

Interessant ist folgender Blog-Eintrag zu dem Thema: 
https://pushstack.wordpress.com/somfy-rts-protocol/

Frame repeat
"When a button is hold pressed the sender will repeat the same code. The frames are separated by the Inter-frame gap. The second and following frames have a hardware sync that consists out of 7 high/low repetitions instead of 2. The repeating frames are identical to the original, the key and rolling code is not increased."

-> kann so ein Frame-Repeat in das TCL Script eingebaut werden?

**Comment by chrkan** [comment]
Hallo habe ich schon öfters von bestimmten Motoren gehört eine Lösung haben wir leider noch nicht gefunden.
https://homematic-forum.de/forum/viewtopic.php?f=37&t=21879&p=343216&hilit=mehrfach#p343216

**Comment by bekaxe** [comment]
Kannst du sagen, wie ich das auf Homematic wiederholt abschicken kann? 
(Die Verknüpfung mit dem Jalousieschalter wird dann schwierig...)

**Comment by chrkan** [comment]
ungetestet:

ersetz mal die Zeile: 

_rega_script  $cmd_

mit:

set x 1

while {$x <3} {
   rega_script  $cmd
    set x [expr {$x + 1}]
}

**Comment by bekaxe** [comment]
Ich habe 
`rega_script $cmd`   

jetzt einfach 4 mal eingefügt. Damit fährt die Jalousie jetzt etwas länger, bleibt dann aber auch stehen. Allerdings habe ich jetzt beim "Doppel"-Klicken mehr Zeit und die Jalousie fährt nach 2x klicken weiter. 

Das Termin-Log liefert jetzt folgende Ausgabe: 
21:35:00 [ttyACM0] <-- YsA02000DEA00004 
21:35:00 [ttyACM0] <-- YsA02000DEA00004 
21:35:00 [ttyACM0] <-- YsA02000DEA00004 
21:35:00 [ttyACM0] <-- YsA02000DEA00004 
21:35:01 [ttyACM0] --> YsA02500DE0400A0 
21:35:02 [ttyACM0] --> YsA02500DE0400A0 
21:35:03 [ttyACM0] --> YsA02500DE0400A0 
21:35:04 [ttyACM0] --> YsA02500DE0400A0

Ist das korrekt, dass 8 Einträge kommen, bei 4x rega_script $cmd? 
oder ist der zweite Eintrag ein "falscher" Stop-Eintrag?

**Comment by chrkan** [comment]
Nein das stimmt schon du schickst 4 mal das ganze

**Comment by bekaxe** [comment]
Ich habe das Problem, dass sich bei Nutzung der Jalousie-Steuerung über den CUL meine Rasperrymatic Installation aufhängt, extrem langsam wird und schließlich keine Rückmeldung mehr gibt. 
kann das durch das geänderte TCL Skript kommen oder gibt es hier weitere Fälle?

**Comment by chrkan** [comment]
Hallo das mag sein, da es nicht das original script ist. Die hm ist bei fehlern in programmen und scripten sehr anfällig
